# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama2 13B training"
world_size = 8

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"
enable_color_printing = true

[model]
name = "llama2"
flavor = "13B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./datasets/tokenizer/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 2
seq_len = 4096
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 1000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
enable_loss_parallel = false
compile = true
dataset = "c4"
gc_freq = 1000
seed = 42
sample_rate = 1.0

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[bittensor]
project = "aesop2"
netuid = 223
bucket = "cont2"
actual_batch_size = 6
device = "cuda"
use_wandb = true
remote = false
debug = false
trace = false
random = false
sync_state = true
baseline = false

[wallet]
name = "Bistro"
hotkey = "M111"

[subtensor]
network = "test"
chain_endpoint = "wss://test.finney.opentensor.ai:443/"